
import React, { Component } from 'react';
import firebase from './firebaseApp';
import DislaySection from './DisplaySelection'

class ReviewMakeup extends Component {
constructor() {
    super();

    this.state = {
    //holds array of input
    submittedData: [],
    //user's input from when they write down their review
    review: ""
    }
}
// getting data from firebase 
componentDidMount() {
    const dbRef = firebase.database().ref('productReviews');
// creating a variable and storing it  
    dbRef.on('value', (response) => {
    const startState = response.val();
    const newState = [];
    //start state is an object so we use for loop to access user's review
    for (let key in startState) {
    const usersInput = {
    //key generated by firebase and post holds input 
        id: key,
        post: startState[key]
    
        }
    //pushing a new user's review into our app
        newState.push(usersInput);
    }
    //updating our component state using newstate
    this.setState({
        submittedData: newState
    })
    })
}

//deals with the textarea input
userPost = (event) => {
    this.setState({
        review: event.target.value
    })
}


//User has submitted their review so they submit an object to firebase
postSubmission = (event) => {
    event.preventDefault();
    const dbRef = firebase.database().ref('productReviews');
    dbRef.push(this.state.review);
    this.setState({
    review: ""
    })
}



//function to remove a review
removeSubmission = (postRemoval) => {
    const dbRef = firebase.database().ref('productReviews');
    dbRef.child(postRemoval).remove();
}

render () {
    return (
    <div className="postSection">
        <form action="submit">
        <input onChange={this.userPost} type="textarea" minLength="20" maxLength="300" value={this.state.review} placeholder="Write a review here!"/>
        <button class="submitButton" onClick={this.postSubmission}>Submit</button>
        </form>

        { this.state.submittedData.map((review) => {
            return (
            <div className="addedUserReview">
                <div key={review.id}></div>
                <p>{review.post}</p>
                <button class="delete" onClick={ () => this.removeSubmission(review.id)}>Delete Review</button>
                
            </div>
            )
        }) }
    </div>
    )
}
}

export default ReviewMakeup;
